# Generated by Django 3.1.1 on 2020-12-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RO_number', models.CharField(max_length=200, unique=True)),
                ('hours_sold', models.DecimalField(decimal_places=2, max_digits=3)),
                ('work_performed', models.TextField()),
                ('completed_date', models.DateField()),
                ('pay_cycle', models.CharField(max_length=10)),
            ],
        ),
    ]
