# Generated by Django 3.1.1 on 2021-03-28 17:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RO_log', '0002_auto_20210323_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ro',
            name='pay_cycle',
        ),
        migrations.AlterField(
            model_name='ro',
            name='RO_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ro',
            name='completed_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 28, 17, 28, 36, 324724, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='PayPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ro',
            name='pay_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='RO_log.payperiod'),
        ),
    ]
