# Generated by Django 3.1.1 on 2021-03-28 17:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('RO_log', '0004_auto_20210328_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='payperiod',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 28, 17, 53, 0, 119694, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='payperiod',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 28, 17, 53, 0, 119694, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ro',
            name='completed_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 28, 17, 53, 0, 119694, tzinfo=utc)),
        ),
    ]
