# Generated by Django 3.1.1 on 2021-03-28 17:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('RO_log', '0005_auto_20210328_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payperiod',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payperiod',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ro',
            name='completed_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 28, 17, 55, 22, 782117, tzinfo=utc)),
        ),
    ]
